package ovh.ecliment.cjee.piloto.domini;
// Generated 26-mar-2018 13:41:13 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.GenericGenerator;

/**
 * Partit generated by hbm2java
 */
@Entity
@Table(name = "PARTIDOS",
         schema = "PUBLIC",
         catalog = "PUBLIC"
)
public class Partit implements java.io.Serializable {

    @Id
    @GenericGenerator(name = "increment", strategy = "increment")
    @GeneratedValue(generator = "increment")
    @Column(name = "ID_PARTIDO", unique = true, nullable = false)
    private Integer idPartit;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_EQUIPO_LOCAL")
    private Equip equipByIdEquipLocal;
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "ID_EQUIPO_VISITANTE")
    private Equip equipByIdEquipVisitant;
    @Column(name = "JORNADA")
    private Integer jornada;
    @Temporal(TemporalType.DATE)
    @Column(name = "FECHA", length = 10)
    private Date data;
    @Column(name = "GOLES_LOCAL")
    private Integer golsLocal;
    @Column(name = "GOLES_VISITANTE")
    private Integer golsVisitant;
    @Column(name = "OBSERVACIONES", length = 500)
    private String observacions;

    public Partit() {
    }

    public Partit(int idPartido) {
        this.idPartit = idPartido;
    }

    public Partit(int idPartido, Equip equiposByIdEquipoLocal, Equip equiposByIdEquipoVisitante, Integer jornada, Date fecha, Integer golesLocal, Integer golesVisitante, String observaciones) {
        this.idPartit = idPartido;
        this.equipByIdEquipLocal = equiposByIdEquipoLocal;
        this.equipByIdEquipVisitant = equiposByIdEquipoVisitante;
        this.jornada = jornada;
        this.data = fecha;
        this.golsLocal = golesLocal;
        this.golsVisitant = golesVisitante;
        this.observacions = observaciones;
    }

    public Integer getIdPartit() {
        return this.idPartit;
    }

    public void setIdPartit(Integer idPartit) {
        this.idPartit = idPartit;
    }

    
    public Equip getEquipsByIdEquipLocal() {
        return this.equipByIdEquipLocal;
    }

    public void setEquipsByIdEquipLocal(Equip equipByIdEquipLocal) {
        this.equipByIdEquipLocal = equipByIdEquipLocal;
    }

    
    public Equip getEquipByIdEquipVisitant() {
        return this.equipByIdEquipVisitant;
    }

    public void setEquipsByIdEquipVisitant(Equip equipByIdEquipVisitant) {
        this.equipByIdEquipVisitant = equipByIdEquipVisitant;
    }

    
    public Integer getJornada() {
        return this.jornada;
    }

    public void setJornada(Integer jornada) {
        this.jornada = jornada;
    }

    
    public Date getData() {
        return this.data;
    }

    public void setData(Date data) {
        this.data = data;
    }

    
    public Integer getGolsLocal() {
        return this.golsLocal;
    }

    public void setGolsLocal(Integer golsLocal) {
        this.golsLocal = golsLocal;
    }

    
    public Integer getGolsVisitant() {
        return this.golsVisitant;
    }

    public void setGolsVisitant(Integer golsVisitant) {
        this.golsVisitant = golsVisitant;
    }

    
    public String getObservacions() {
        return this.observacions;
    }

    public void setObservacions(String observacions) {
        this.observacions = observacions;
    }

}
